name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish-node-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Build and publish to npm registry
        continue-on-error: true
        run:
          npm ci &&
          npm run build &&
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: "@baselime"
  
      - run: echo "registry=https://npm.pkg.github.com/@baselime" >> .npmrc
  
      - name: Publish to GitHub registry
        continue-on-error: true
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-release:
    needs: [publish-node-packages]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set current date
        run: |
          echo "RELEASE_DATE=$(date +"%d %B %Y")" >> $GITHUB_ENV
      
      - name: Get version from tag
        id: tag_name
        run: |
          echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_level: none
          version: ${{ steps.tag_name.outputs.current_version }}
          path: ./CHANGELOG.md

      - name: Compute checksums
        run: |
          echo "## ${{ env.RELEASE_VERSION }} (${{ env.RELEASE_DATE }})" >> checksums.md
          echo "${{ steps.changelog_reader.outputs.changes }}" >> checksums.md
          echo "" >> checksums.md
          echo "" >> checksums.md

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          body_path: checksums.md
          files: |
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify-community:
    needs: [create-release]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get version from tag
        id: tag_name
        run: |
          echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}
      - name: Post to the community Slack channel
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C04KT9JNRHS'
          payload: |
            {
              "text": "[Release] Baselime Opentelemetry for Node.JS v${{ steps.tag_name.outputs.current_version }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*[Release] Baselime Opentelemetry for Node.JS v${{ steps.tag_name.outputs.current_version }}*"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<https://github.com/Baselime/node-opentelemetry/releases/tag/v${{ steps.tag_name.outputs.current_version }}|https://github.com/Baselime/node-opentelemetry/releases/tag/v${{ steps.tag_name.outputs.current_version }}>"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}